[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_NEXT_PLUGIN_SKIP_IMAGE_COMPRESSION = "true"

[functions]
  external_node_modules = [
    "@xenova/transformers",
    "sharp",
    "@img/sharp-linux-x64",
    "@img/sharp-libvips-linux-x64"
  ]
